### ISSUE TITLE
Centos Compatible

### ISSUE THREAD

**Issue by joseph-greer** [toppic-suite/toppic-suite#1]
Is toppic compatible with Centos? I've tried to install it with versions 7 and 7.5 without success. I think I've been able to track down most of the packages.

Also, one of the first errors I received related to c++ 14. Is c++ required. The README mentions c++ 11.

**Comment by veeraprt** [comment]
I am trying with the below dependencies in Centos-7. Even though, getting so many issues during compilation.

gcc/11.2.0 
boost/1.75.0-openmpi-4.0.5-gcc-10.2.0
 cmake/3.15.4 
eigen/3.3.4 
xerces-c/3.2.3 
qt/5.10.1

After fixing a lot of issues, still getting the below error since I have loaded/set the required environment modules:

cannot find -lQt5Widgets
cannot find -lQt5Core
cannot find -lQt5Gui
cannot find -lxerces-c

Another issue is every time the "make" process starts from first (1%)

**Comment by veeraprt** [comment]
Now I have recompiled qt-5.12.0 with static library and also set the environment as shown below.

export LDFLAGS="$LDFLAGS -L/software/supplemental/xerces-c/3.2.3/lib"

It's compiled successfully.

**Comment by liuxiaowen** [comment]
Please use a Ubuntu docker to compile it.

**Comment by liuxiaowen** [comment]
Please find compilation steps for CentOS in README.
